#!/bin/bash
# Darknet Canary Testing Wrapper
#
# Orchestrates Phase 1 of DNET_CANARY_PROTOCOL.md:
# - Kills scorecard (eliminates interference variable)
# - Runs single-manager test 3 times with 30-min waits
# - Monitors CPU, API health, game responsiveness
# - Logs results to docs/darknet-canary-log.md
# - Stops immediately on freeze detection
#
# Prerequisites (from protocol):
# - MCP running stable for 30+ minutes
# - Remote API daemon connected
# - Recovery plan ready (Ken has dnet_killswarm.js)
#
# Usage:
#   bash tools/dnet_canary_test.sh [--phase 1|2|3] [--runs N]
#
# Examples:
#   bash tools/dnet_canary_test.sh                    # Phase 1, 3 runs
#   bash tools/dnet_canary_test.sh --phase 1 --runs 1 # Single test run

set -e

REPO_DIR="/Users/Shared/BitBurner"
LOG_FILE="${REPO_DIR}/docs/darknet-canary-log.md"
CONTROL_PORT=${CONTROL_PORT:-12527}
PHASE=${PHASE:-1}
NUM_RUNS=${NUM_RUNS:-3}
PHASE_1_DURATION=300          # 5 minutes in seconds
PHASE_1_INTERVAL=1800         # 30 minutes between runs
CPU_SPIKE_THRESHOLD=120       # Percent (>120% = stop)
CHECK_INTERVAL=10             # Seconds between CPU checks

# Color codes
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
RESET='\033[0m'

# Logging
log() {
  echo -e "${GREEN}[$(date +'%H:%M:%S')]${RESET} $*"
}

warn() {
  echo -e "${YELLOW}[$(date +'%H:%M:%S')] ⚠️  $*${RESET}"
}

error() {
  echo -e "${RED}[$(date +'%H:%M:%S')] ❌ $*${RESET}"
}

# Log to markdown file
log_to_file() {
  echo "$1" >> "$LOG_FILE"
}

# Initialize log
init_log() {
  if [ ! -f "$LOG_FILE" ]; then
    mkdir -p "$(dirname "$LOG_FILE")"
    cat > "$LOG_FILE" << 'EOF'
# Darknet Canary Test Log

Generated by `tools/dnet_canary_test.sh`

---

EOF
  fi
}

# Parse arguments
parse_args() {
  while [ $# -gt 0 ]; do
    case "$1" in
      --phase)
        PHASE="$2"
        shift 2
        ;;
      --runs)
        NUM_RUNS="$2"
        shift 2
        ;;
      *)
        error "Unknown argument: $1"
        exit 1
        ;;
    esac
  done
}

# Check prerequisites
check_prerequisites() {
  log "Checking prerequisites..."

  # Check MCP is running
  if ! python3 "$REPO_DIR/tools/bb_remote.py" ctl-status --control-port "$CONTROL_PORT" &>/dev/null; then
    error "Remote API daemon not responding on port $CONTROL_PORT"
    error "Start daemon first: nohup python3 tools/bb_remote.py daemon --port 12526 --control-port 12527 &"
    exit 1
  fi
  log "✅ Remote API daemon responsive"

  # Check game is running (via Remote API)
  if ! python3 "$REPO_DIR/tools/bb_remote.py" ctl-status --control-port "$CONTROL_PORT" 2>&1 | grep -q '"connected": true'; then
    error "Game not connected to Remote API"
    error "In Bitburner, open Options → Remote API and click Connect"
    exit 1
  fi
  log "✅ Game connected to Remote API"
}

# Kill scorecard before testing
kill_scorecard() {
  log "Killing dnet_scorecard.js (if running)..."
  if pgrep -f "dnet_scorecard.js" > /dev/null 2>&1; then
    # Use Remote API to kill it in-game
    python3 "$REPO_DIR/tools/bb_remote.py" ctl-kill dnet_scorecard.js --control-port "$CONTROL_PORT" 2>/dev/null || true
    sleep 1
    log "✅ Scorecard terminated"
  else
    log "ℹ️  Scorecard not running"
  fi
}

# Get current CPU usage
get_cpu_usage() {
  # Get Bitburner process CPU %
  ps aux | grep "Bitburner\|electron" | grep -v grep | awk '{print $3}' | head -1
}

# Monitor CPU during test
monitor_cpu() {
  local duration=$1
  local start_time=$(date +%s)
  local max_cpu=0
  local freeze_detected=0

  log "Monitoring CPU for ${duration}s..."

  while true; do
    local current_time=$(date +%s)
    local elapsed=$((current_time - start_time))

    if [ $elapsed -ge $duration ]; then
      break
    fi

    local cpu=$(get_cpu_usage)
    if [ -n "$cpu" ]; then
      cpu_int=$(echo "$cpu" | cut -d. -f1)
      if [ "$cpu_int" -gt "$max_cpu" ]; then
        max_cpu="$cpu_int"
      fi

      if [ "$cpu_int" -gt "$CPU_SPIKE_THRESHOLD" ]; then
        warn "CPU spike detected: ${cpu}% (threshold: ${CPU_SPIKE_THRESHOLD}%)"
        freeze_detected=1
        break
      fi
    fi

    sleep "$CHECK_INTERVAL"
  done

  echo "$max_cpu"
  return $freeze_detected
}

# Get manager count from registry
get_manager_count() {
  if [ -f "$REPO_DIR/dnet_manager_registry.json" ]; then
    python3 << 'PYEOF'
import json
try:
    with open("/Users/Shared/BitBurner/dnet_manager_registry.json") as f:
        data = json.load(f)
        managers = [k for k in data.keys() if k.startswith("host_")]
        print(len(managers))
except:
    print("0")
PYEOF
  else
    echo "0"
  fi
}

# Run single canary test
run_canary() {
  local run_num=$1
  local phase=$2
  local duration=$PHASE_1_DURATION

  log ""
  log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log "Phase $phase Canary Run $run_num / $NUM_RUNS"
  log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  local test_start=$(date +'%Y-%m-%d %H:%M:%S')
  local timestamp=$(date +%s)

  log_to_file ""
  log_to_file "## Phase $phase - Run $run_num - $test_start"
  log_to_file ""
  log_to_file "| Field | Value |"
  log_to_file "|-------|-------|"
  log_to_file "| Duration | ${duration}s |"
  log_to_file "| Started | $test_start |"

  # Trigger dnet_root.js in-game (Ken must do this, or we use Remote API)
  log "Launching dnet_root.js via Remote API..."
  python3 "$REPO_DIR/tools/bb_remote.py" ctl-restart --control-port "$CONTROL_PORT" 2>&1 | head -3 || true

  sleep 5  # Give it time to start

  # Monitor CPU
  local cpu_peak
  cpu_peak=$(monitor_cpu $duration) || {
    error "Freeze detected during test!"
    log_to_file "| Status | ❌ FREEZE DETECTED |"
    return 1
  }

  sleep 2

  local manager_count=$(get_manager_count)
  local test_end=$(date +'%Y-%m-%d %H:%M:%S')

  log_to_file "| Manager Count (Final) | $manager_count |"
  log_to_file "| CPU Peak | ${cpu_peak}% |"
  log_to_file "| Ended | $test_end |"
  log_to_file "| Status | ✅ SUCCESS |"

  log "✅ Test completed: CPU peak ${cpu_peak}%, ${manager_count} managers"

  # Kill darknet after test
  log "Cleaning up darknet processes..."
  python3 "$REPO_DIR/tools/bb_remote.py" ctl-kill dnet_root.js --control-port "$CONTROL_PORT" 2>/dev/null || true
  sleep 2

  return 0
}

# Main
parse_args "$@"
init_log
check_prerequisites
kill_scorecard

log ""
log "Starting Phase $PHASE Canary Protocol ($NUM_RUNS runs)"
log "Duration per run: $PHASE_1_DURATION seconds"
log "Interval between runs: $((PHASE_1_INTERVAL / 60)) minutes"
log ""

log_to_file "## Test Session - $(date +'%Y-%m-%d %H:%M:%S')"
log_to_file ""
log_to_file "**Phase**: $PHASE  "
log_to_file "**Runs**: $NUM_RUNS  "
log_to_file "**Duration per run**: ${PHASE_1_DURATION}s  "
log_to_file ""

for i in $(seq 1 "$NUM_RUNS"); do
  if ! run_canary "$i" "$PHASE"; then
    error "Test failed! Check logs at $LOG_FILE"
    log_to_file ""
    log_to_file "**PROTOCOL HALTED**: Freeze detected at run $i. Do not attempt higher manager counts."
    exit 1
  fi

  if [ $i -lt "$NUM_RUNS" ]; then
    log ""
    log "Waiting $((PHASE_1_INTERVAL / 60)) minutes before next run..."
    sleep "$PHASE_1_INTERVAL"
  fi
done

log ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅ Phase $PHASE Canary Complete - All $NUM_RUNS runs successful"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

log_to_file ""
log_to_file "---"
log_to_file ""
log_to_file "✅ **Phase $PHASE Complete**: All runs successful, no freezes detected."
log ""
log "Results logged to: $LOG_FILE"
